name: "tasks"
services:
  backend:
    build: .
    depends_on:
      - mysqldb
    restart: always
    networks:
      - loadbalancing
      - mysql
    deploy:
      replicas: 4
  mysqldb:
    container_name: "mysql"
    image: mysql:latest
    networks:
      - mysql
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tasks
      MYSQL_USER: spring_user
      MYSQL_PASSWORD: spring_user_password
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    networks:
      - loadbalancing
    depends_on:
      - backend
volumes:
  mysql-data:
networks:
  loadbalancing:
  mysql:
